### ISSUE TITLE
Compilation fails for programs that use generic functions with loops

### ISSUE THREAD

**Issue by fmoletta** [lambdaclass/cairo_native#398]
Minimal example:
```
fn main() -> (u16, u64) {
    (
        bar(3),
        bar(5),
    )
}

fn bar<T, +Drop<T>>(a: T) -> T {
    loop {
        break;
    };
   a
}
```
Fails with: `error: redefinition of symbol named 'generic_fn_loop::generic_fn_loop::bar[expr0]`

This bug causes the tests using `alexandria_encoding::reverse_bits` & `alexandria_encoding::reverse_bytess` functions to fail  in #394
